
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:@localhost:3306/liar'
SQLALCHEMY_COMMIT_ON_TEARDOWN = True

CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'

SQLALCHEMY_TRACK_MODIFICATIONS = False
JSON_AS_ASCII=False